// Barrel export for the shared UI layer (renderer/ui/*).
export { Toggle, type ToggleProps } from './Toggle'
export { Segmented, type SegmentedProps, type SegmentedOption } from './Segmented'
export { KeyCard, type KeyCardProps } from './KeyCard'
export { PageHeader, type PageHeaderProps } from './PageHeader'
export { EmptyState, type EmptyStateProps } from './EmptyState'
export { LoadingDots } from './LoadingDots'
export { ProviderGlyph, type ProviderGlyphProps } from './ProviderGlyph'
export { Kbd } from './Kbd'
export * from './glyphs'
export { LANGUAGES } from './data/languages'
export { IS_MAC, IS_WIN, IS_LINUX } from './data/platform'
export { dictationBindingLabel, instructionKeyLabel, modifierLabel } from './data/keyLabels'
